### ISSUE TITLE
Template is not working on device (phone)

### ISSUE THREAD

**Issue by yusufguleryuz** [framework7io/framework7-template-vue-simple#5]
Hi, i downloaded all files after build at build.phonegap.com. Then i installed that apk but not working vue template....  i think device can not compile vue template file.

P.s: All files are working localhost, or web but not working at device(apk --->phone).

What can i do?

**Comment by nuxcasino** [comment]
@yusufguleryuz  

After creating a Cordova project, navigate to the project directory. From the project directory, you need to add a platform for which you want to build your app.
To add a platform, type `cordova platform add <platform name>`
more http://cordova.apache.org/#getstarted
