### ISSUE TITLE
Unable to install Vue-meta Plugin

### ISSUE THREAD

**Issue by jaideepghosh** [framework7io/framework7-template-vue-simple#6]
I'm trying to install vue-meta plugin in this example, but in console it is returning error message: 
`Unexpected identifier`

Please help me to resolve this issue.

**Comment by jaideepghosh** [comment]
Hey @nolimits4web ,

Issue is not yet resolved.
Waiting for your response.

**Comment by nolimits4web** [comment]
@jaideepghosh not really related to template itself
