### ISSUE TITLE
Doesn't seem to support back when 2 levels deep...

### ISSUE THREAD

**Issue by MattFellows** [framework7io/framework7-template-vue-simple#7]
Adding an extra "page" in, such as `About2`, linked to from the `About` "page" breaks the back navigation...

e.g.
in www/index.html modify the about markup
```
<template id="page-about">
    <f7-page>
      <f7-navbar title="About" back-link="Back"></f7-navbar>
      <f7-block-title>About My App</f7-block-title>
      <f7-block strong>
        <p>Here is About page!</p>
        <f7-list>
                <f7-list-item link="/about2/">About 2</f7-list-item>
        </f7-list>
        <p>You can go <f7-link back>back</f7-link>.</p>
        <p>Mauris posuere sit amet metus id venenatis. Ut ante dolor, tempor nec commodo rutrum, varius at sem. Nullam ac nisi non neque ornare pretium. Nulla mauris mauris, consequat et elementum sit amet, egestas sed orci. In hac habitasse platea dictumst.</p>
        <p>Fusce eros lectus, accumsan eget mi vel, iaculis tincidunt felis. Nulla tincidunt pharetra sagittis. Fusce in felis eros. Nulla sit amet aliquam lorem, et gravida ipsum. Mauris consectetur nisl non sollicitudin tristique. Praesent vitae metus ac quam rhoncus mattis vel et nisi. Aenean aliquet, felis quis dignissim iaculis, lectus quam tincidunt ligula, et venenatis turpis risus sed lorem. Morbi eu metus elit. Ut vel diam dolor.</p>
      </f7-block>
    </f7-page>
  </template>
```
and adding another template for `about2`
```


  <template id="page-about-2">
    <f7-page>
      <f7-navbar title="About 2" back-link="Back"></f7-navbar>
      <f7-block-title>About 2 My App</f7-block-title>
      <f7-block strong>
        <p>Here is About page 2!</p>
        <p>You can go <f7-link back>back</f7-link>.</p>
        <p>Mauris posuere sit amet metus id venenatis. Ut ante dolor, tempor nec commodo rutrum, varius at sem. Nullam ac nisi non neque ornare pretium. Nulla mauris mauris, consequat et elementum sit amet, egestas sed orci. In hac habitasse platea dictumst.</p>
        <p>Fusce eros lectus, accumsan eget mi vel, iaculis tincidunt felis. Nulla tincidunt pharetra sagittis. Fusce in felis eros. Nulla sit amet aliquam lorem, et gravida ipsum. Mauris consectetur nisl non sollicitudin tristique. Praesent vitae metus ac quam rhoncus mattis vel et nisi. Aenean aliquet, felis quis dignissim iaculis, lectus quam tincidunt ligula, et venenatis turpis risus sed lorem. Morbi eu metus elit. Ut vel diam dolor.</p>
      </f7-block>
    </f7-page>
  </template>
```

Then adding in the component  for `/about2/` to the initialisation in app.js
```
Vue.component('page-about-2', {
  template: '#page-about-2'
});
```
and the route:
```
          {
            path: '/about2/',
            component: 'page-about-2'
          }
```

Then clicking the link for "/about/" and subsequently clicking the new link to "/about2/" lets you navigate 'back' once, but then hitting 'back' again gets a 404...

**Comment by nolimits4web** [comment]
Make sure you have put your home page into route and component too

**Comment by MattFellows** [comment]
Aha - I was about to comment, that if I added in `about3` it can get back to `about`, so it's not a number of levels thing...  
How would I add the homepage in as a component / route to it? I assume I add a route for `'/'` but what component would it link to? `this`?

**Comment by MattFellows** [comment]
I've also tried creating a component pointing at '#app' as its template but that also didn't work...
```
Vue.component('app', {
  template: '#app'
});
```
and
```
{
            path: '/',
            component: 'app'
},
```

I'm fairly certain about routing '/' is the correct thing, but not sure about how to reference the main app as the component?

**Comment by nolimits4web** [comment]
You should link home page component. Look how it is done on webpack template https://github.com/framework7io/framework7-template-vue-webpack/blob/master/src/routes.js

**Comment by MattFellows** [comment]
Thanks @nolimits4web really appreciate you responding, but I'm using the framework7-template-vue-simple template because it's a really simple app and so it's not being transpiled...  I'm not sure how to turn that webpack example into something that works in native JS?

**Comment by MattFellows** [comment]
FYI: in case it's a more appropriate place I've also asked this question on stackoverflow: https://stackoverflow.com/questions/53318433/reference-index-home-main-view-in-framework7-vue-simple-project-for-route

**Comment by MattFellows** [comment]
If this isn't possible, or it's not known how to do it, I'd much rather know, so I can work on changing the project out to the webpack version?   Are there any thoughts?

**Comment by nolimits4web** [comment]
Just do it like with other pages. So make a component for home page, e.g.:

```
<template id="page-home">
    <f7-page>
      ...
    </f7-page>
  </template>
```
Register it:
```
Vue.component('page-home', {
  template: '#page-home'
});
```


Then keep app's View empty:
```
<f7-app>
  ...
  <f7-view main url="/"></f7-view>
</f7-app>
```

And specify route for home page:
```
{
  path: '/',
  component: 'page-home',
}

**Comment by MattFellows** [comment]
Perfect - that step of leaving the main view empty, but using the `url-"/"` was the vital missing step in my understanding - Much appreciated
