### ISSUE TITLE
Is this use deprecated framework7-vue?

### ISSUE THREAD

**Issue by aalfiann** [framework7io/framework7-template-vue-simple#8]
I've just create very simple app and it is work.

But I've just visit to https://github.com/framework7io/framework7-vue and see the title that it was deprecated? Is that true?

So I need your answer so I can stop my vue project and use F7 with React.

Thanks.

**Comment by nolimits4web** [comment]
Repository is deprecated, not the project. Follow documentation at framework7.io/vue/
